version: "3.8"
services:
  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: ${ELK_VERSION}
    hostname: kibana
    volumes:
      - type: bind
        source: ./kibana/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    environment:
      - ELASTICSEARCH_USERNAME=usedesk
      - ELASTICSEARCH_PASSWORD=usedesk
    ports:
      - 5601:5601
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:5601 || exit 1"
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    networks:
      - elastic